// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7eV5OZxHsgkSouKGp5b-RmpUa_ALqAw8',
    appId: '1:690598803810:web:75baba04219b5a54be143b',
    messagingSenderId: '690598803810',
    projectId: 'money-manager-6ac3d',
    authDomain: 'money-manager-6ac3d.firebaseapp.com',
    storageBucket: 'money-manager-6ac3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2LiwuPyiIDP0Fy3uj8VESYoi_UKgeoPE',
    appId: '1:690598803810:android:ad1450e10fb454d7be143b',
    messagingSenderId: '690598803810',
    projectId: 'money-manager-6ac3d',
    storageBucket: 'money-manager-6ac3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJs3orSLbyu-aSlr-E-h0mLEsYcwjmooU',
    appId: '1:690598803810:ios:d40d2e02eb87bea3be143b',
    messagingSenderId: '690598803810',
    projectId: 'money-manager-6ac3d',
    storageBucket: 'money-manager-6ac3d.appspot.com',
    iosBundleId: 'com.example.moneyManager',
  );

}